### ISSUE TITLE
feat: support "AE" type in sendResponse()

### ISSUE THREAD

**Issue by jtarvainen** [Bugs5382/node-hl7-server#100]
# Feature Request

**Describe the Feature Request**

`sendResponse()` only supports type values "AA" (Application Accept) or "AR" (Application Reject); the value "AE" (Application Error) is only used if formulating a response fails.

The "AR" type is commonly interpreted to indicate issues with the MSH-9, MSH-11 and/or MSH-12 fields. As such, it may not be applicable if the message itself is valid but cannot be processed for some other reason (e.g. the data not being relevant to the recipient).

We have a client device that expects to receive a response of type "AE" in case of errors not related to message validity. Please add support for setting this response type manually.

**Describe Preferred Solution**

Add "AE" as one of the accepted response types in `sendResponse`. Note that `_createAckMessage` should construct the MSA segment of the "AE" response in the same way as that of the other response types:

```
    const segment = ackMessage.addSegment('MSA')
    segment.set('1', type) // <-- this should also allow "AE"
    segment.set('2', message.get('MSH.10').toString())
```

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by Bugs5382** [comment]
@jtarvainen Approved!

**Comment by Bugs5382** [comment]
@jtarvainen Care to review the code I just pushed up?

**Comment by jtarvainen** [comment]
@Bugs5382 Thanks for taking care of this so fast! I checked out the change; looks good to me! 👍

**Comment by Bugs5382** [comment]
@jtarvainen I give develop at least a few days for testing so this way medical applications are good.
