### ISSUE TITLE
fix: loadedMessage is not cleared after message(s) handled

### ISSUE THREAD

**Issue by jtarvainen** [Bugs5382/node-hl7-server#102]
## Environment

-   HL7 Client version: 2.3.1
-   HL7 Server version: 2.4.1

Questions:

- Are you using the Node [HL7 Server](https://github.com/Bugs5382/node-hl7-server) package as your HL7 Server to connect to or a 3rd party system?

Yes

## Expected Behavior

The `Inbound` instance's "data" event handler should clear `loadedMessage` after handling a complete message (or batch of messages). Otherwise the variable just keeps concatenating each received message in perpetuity.

## Actual Behavior

`loadedMessage` is never cleared, causing each previously received message to be re-handled upon reception of each new message.

The fix is to add the following after row 220 in `src/server/inbound.ts`:

```
loadedMessage = '';
```

## Steps to reproduce the bug

Create a unit test where:

1. Client initiates a connection to the server
2. Client sends a message to the server and waits for a response (connection is kept open!)
3. Client sends a second message to server and waits for a response
4. Client closes the connection to the server

Assert that in step #3 the previously sent message is re-handled on the server in addition to the new message and two acknowledgments are sent to the client instead of one.

**Comment by Bugs5382** [comment]
@jtarvainen My coding days are tomorrow. I will work on this and release the other feature for AE.

**Comment by Bugs5382** [comment]
So doing so breaks up a unit test for very large messages, like getting PDF data.

https://github.com/Bugs5382/node-hl7-server/blob/9eb9a200e8e40b3b7467646defbec7f5e17ba82e/src/server/inbound.ts#L139

Already has clearing of the loadedMessage on a TCP connect. I might have to write a unit test out for this one to test out this issue.

**Comment by Bugs5382** [comment]
This could be a bug in the node-hl7-client as well.

**Comment by jtarvainen** [comment]
The client device we use keeps the TCP connection alive between messages, so we can't rely on the clear-on-connect feature.

**Comment by Bugs5382** [comment]
@jtarvainen  Just so you know, I am trying to nail this down. Some major testing I been writing locally.

**Comment by jtarvainen** [comment]
@Bugs5382 Any update on this? I haven't investigated the code further, but to me it sounds like it should be OK to clear `loadedMessage` after the current message has been fully processed, even if it contains PDF data?

**Comment by Bugs5382** [comment]
@jtarvainen I am still working. I tried that, and my unit tests failed hard. Maybe I am missing something.

**Comment by Bugs5382** [comment]
This fix is going to be out soon. Thanks @jtarvainen  for your patience.

**Comment by Bugs5382** [comment]
@jtarvainen  This has been release 3.0.1-develop

**Comment by jtarvainen** [comment]
That's great, thank you!
