### ISSUE TITLE
feat: Allow overriding response MSH content

### ISSUE THREAD

**Issue by jtarvainen** [Bugs5382/node-hl7-server#103]
# Feature Request

The MSH content set by the `_createAckMessage` method in the `SendResponse` class with HL7 spec 2.5.1 does not match what our device (Roche cobas c 303) expects to receive, in the following ways:

- **MSH-7**: timestamp format is currently set to YYYYMMDDHHMMSS (e.g. "20240821180000"), but in our case it should be YYYYMMDDHHMMSSQZZzz (e.g. "20240821180000+0300"), i.e. with timezone information included (+ or - sign followed by exactly four numbers)
- **MSH-10**: this field is hardcoded to "ACK", but in our case it should be a unique Message Control ID (20-character GUID)
- **MSH-18**: this field is not set, but in our case it should be "UNICODE UTF-8"
- **MSH-21**: this field is not set, but in our case it should be a copy of the MSH-21 field of the message being acknowledged

**Describe Preferred Solution**

Allow the user to override either a specific set of MSH fields (of the user's choosing), or the entire MSH segment, as an argument to `sendResponse`.

With this change, the existing `_overrideMSH` argument, which only affects the MSH-9.3 field, could be replaced by a more comprehensive solution.

Please also check if the current implementation (2.4.1 at the time of writing) does not follow the general HL7 spec in some way, meaning that the default value should be changed as well.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

**Comment by Bugs5382** [comment]
@jtarvainen  I have to think about how to do this. Any PR you want to suggest, feel free to do so. This might cause a breaking change.

**Comment by jtarvainen** [comment]
> @jtarvainen I have to think about how to do this. Any PR you want to suggest, feel free to do so. This might cause a breaking change.

OK, I'll give it a shot!

**Comment by jtarvainen** [comment]
@Bugs5382 I cloned the repo with SSH and made the changes locally in a new branch created from the `develop` branch. I then tried to push my branch to the remote, but couldn't:

>ERROR: Permission to Bugs5382/node-hl7-server.git denied to jtarvainen.

Should this work?

**Comment by jtarvainen** [comment]
@Bugs5382 I created a pull request for this: https://github.com/Bugs5382/node-hl7-server/pull/106

**Comment by Bugs5382** [comment]
@jtarvainen  3.0.0-beta.1 is out. 👍   I will release it out to the wild by the end of the weekend.

**Comment by jtarvainen** [comment]
Great, thanks!
