### ISSUE TITLE
loadedMessage not concatenated

### ISSUE THREAD

**Issue by krisc-informatica** [Bugs5382/node-hl7-server#60]
In server/inbound.js the loadedMessages is set to the currently received buffer. Shouldn't the buffer not be concatenated to the loadedMessage instead (line 101):

`loadedMessage **+=** buffer.toString().replace(PROTOCOL_MLLP_HEADER, '');`

**Comment by Bugs5382** [comment]
I will review tonight and have a fix out maybe by the end of the week.

**Comment by Bugs5382** [comment]
@krisc-informatica It could be there. I clear out the previous message or "reset" it each time it gets a message. I made this so the buffer didn't get too large and had a memory leak. I don't think there is an issue. Adding it doesn't do any harm.

**Comment by seanjb** [comment]
We have actually just run into a problem with this issue. As the loadedMessage is not concatenated as @krisc-informatica  suggests, longer messages fail to be received by the server. Specific example would be a HL7 message with encapsulated data. 

For larger messages only the last "chunk" is received and understandably causes an error as the original MSH segment and other prior segments are missing. 

Changing this to a concatenation approach appears to resolve the issue.

**Comment by Bugs5382** [comment]
@seanjb Reviewing now!

**Comment by Bugs5382** [comment]
@seanjb Can you try https://www.npmjs.com/package/node-hl7-server/v/2.4.1-beta.1? Before, again, I publish to the wild.

**Comment by seanjb** [comment]
2.4.1 tested and confirmed working!
